### ISSUE TITLE
Creative commons attribution label and licence logo issues

### ISSUE THREAD

**Issue by Hitcher** [jurialmunkey/script.wikipedia#6]
1. When using a label control for the attribution label (ID=9904) the list (ID=9902) and image (Window.Property(Image)) won't display. Only a textbox works.
2. Although the licence logo (ID=9905) is meant to be optional not displaying it causes the whole script to be empty.

**Comment by jurialmunkey** [comment]
Because it's a scripted window you have to use the same ids and control types as the script expects. 

Basically you must have the logo control because the script expects it to exist but licensing does not require you to display it on screen eg you could use a conditional fade, or place it off screen. I think visible set to false also works but haven't tested.

Same thing goes with the textbox control. Because the script identifies it as a textbox it must be a textbox otherwise the script will break and have weird behaviour as Kodi's interfaces for interacting with a textbox and label control are different.

**Comment by Hitcher** [comment]
> Basically you must have the logo control because the script expects it to exist but licensing does not require you to display it on screen eg you could use a conditional fade, or place it off screen. I think visible set to false also works but haven't tested.

Yes, hiding it works.

> Same thing goes with the textbox control. Because the script identifies it as a textbox it must be a textbox otherwise the script will break and have weird behaviour as Kodi's interfaces for interacting with a textbox and label control are different.

What's confusing is the [Required controls](https://github.com/jurialmunkey/script.wikipedia?tab=readme-ov-file#required-controls) have it listed as a label control not a textbox.

**Comment by jurialmunkey** [comment]
Readme fixed. Thanks.
